# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.8
loader_version=0.15.6
ae2_version=15.0.3-alpha
jei_version=15.2.0.27

# Mod Properties
mod_version=3.0.7-1.20.1
fabric_mod_version=3.0.8-1.20.1-Fabric
forge_mod_version=3.0.8-1.20.1-Forge
maven_group=com.skniro
mod_author=skniro
archives_base_name=GrowableOres
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.92.3+1.20.1
forge_version=1.20.1-47.3.22
forge_version_range=[46,)
loader_version_range=[2,)

minecraft_version_range=[1.20,1.21)
mod_id=growableores
mod_name=Skniro's GrowableOres
mod_license=MIT License
mod_group_id=com.skniro.growableores
mod_description=Add some growable ores.
mod_authors=skniro















