# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=26.2
loader_version=0.19.3
ae2_version=15.0.3-alpha
skniro_lib_version=1.0.0

# Mod Properties
mod_version=3.8.0.beta.2-26.2-Fabric
forge_mod_version=3.8.0.beta.2-26.2-Forge
neoforge_mod_version=3.8.0.beta.2-26.2-NeoForge
maven_group=com.skniro
archives_base_name=GrowableOres
mod_author=skniro
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.152.1+26.2
forge_version=65.1.2
forge_version_range=[46,)

jei_version=15.2.0.22

# Neoforge Properties
minecraft_version_range=[26.2,26.3)
mod_id=growable_ores
mod_name=Skniro's GrowableOres
mod_license=MIT License
mod_group_id=com.skniro.growableores
mod_description=Add some growable ores.
mod_authors=skniro

# Neoforge
neo_version=26.2.0.67
neo_version_range=[26.1.0.20,)
loader_version_range=[2,)







